name: rubiks_web
description: An absolute bare-bones web app.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.18.0 <3.0.0'

# dependencies:
#   path: ^1.7.0
dependencies:
  rubiks_core:
    path: ../rubiks_core

flutter:
  assets: 
    - packages/rubiks_core/data/
    - ./data/

dev_dependencies:
  build_runner: ^2.1.4
  build_web_compilers: ^3.2.1
  lints: ^2.0.0
